### PR TITLE
Chapter1 quantum interference

### PR DESCRIPTION
**Pull request by homefish**
Add three fixes in **Chapter 1 Quantum inteference**:

- 1.4 Interferometers: Add missing term and intermediate steps.
- 1.7 Computation: Add missing factor of 2 and intermediate steps.
- 1.10.3 Many computational paths: Fix exponents to satisfy P=1 condition.

### CODE REVIEW

**Comment by thosgood** [comment]
thanks for this! I'm currently on holiday, but I'll take a proper look and merge the changes when I get back :)

**Comment by thosgood** [comment]
I think I'm just having a slow day, but could you explain the change in 1.10.3? It seems like we do want $\frac{1}{\sqrt{n}}e^{ik\varphi}$, since this gives probability $\frac{1}{n}$ for each computational path, no?

**Comment by homefish** [comment]
> I think I'm just having a slow day, but could you explain the change in 1.10.3? It seems like we do want $\frac{1}{\sqrt{n}}e^{ik\varphi}$, since this gives probability $\frac{1}{n}$ for each computational path, no?


Suppose we use the original expression with $\frac{1}{\sqrt{n}}$, i.e.

$$
\psi = \sum_{k=0}^{n-1}\frac{1}{\sqrt{n}}e^{ik\varphi}
$$

Let $\varphi = 0$. Then 

$$
\psi = \sum_{k=0}^{n-1}\frac{1}{\sqrt{n}}e^{ik\varphi} = \sum_{k=0}^{n-1}\frac{1}{\sqrt{n}}1 = \frac{1}{\sqrt{n}} \sum_{k=0}^{n-1}1 = \frac{n}{\sqrt{n}} = \sqrt{n}
$$

It follows that $P = |\psi|^2 = n$.
For $n > 1$ we get $P > 1$. However, we require $P = 1$ for $\varphi = 0$. Also, the probability must not exceed 1.

See these three plots for $P$ as a function of $\varphi$ and $n = 5$ showing that $P$ exceeds 1:

a) Plotting $$P = |\psi|^2 = |\sum_{k=0}^{n-1}\frac{1}{\sqrt{n}}e^{ik\varphi}|^2 :$$

https://www.wolframalpha.com/input?i=plot+1%2F5+*+%7C1+%2B+e%5E%28i*phi%29+%2B+e%5E%28i*phi*2%29%2Be%5E%28i*phi*3%29%2Be%5E%28i*phi*4%29%7C%5E2+for+phi%3D0+to+2*pi

b) Plotting $P = \frac{1}{n}\left\vert \frac{1-e^{i n\varphi}}{1-e^{i\varphi}} \right\vert^2$

https://www.wolframalpha.com/input?i=plot+1%2F5+*+%7C%281+-+e%5E%28i*5*phi%29%29%2F%281-e%5E%28i*phi%29%29%7C%5E2+for+phi+%3D+0+to+2*pi


c) Plotting $P = \frac{1}{n} \frac{\sin^2 (n\frac{\varphi}{2})}{\sin^2 (\frac{\varphi}{2})}.$


https://www.wolframalpha.com/input?i=plot+1%2F5+*+sin%5E2%285*phi%2F2%29%2Fsin%5E2%28phi%2F2%29+for+phi%3D0+to+2*pi


------------------------------------------------------------


Suppose we use $\frac{1}{n}$ instead of $\frac{1}{\sqrt{n}}$, i.e.

$$\psi = \sum_{k=0}^{n-1}\frac{1}{n}e^{ik\varphi}$$

Let $\varphi = 0$. Then 

$$
\psi = \sum_{k=0}^{n-1}\frac{1}{n}e^{ik\varphi} = \sum_{k=0}^{n-1}\frac{1}{n}1 = \frac{1}{n} \sum_{k=0}^{n-1}1 = \frac{n}{n} = 1
$$

It follows that $P = |\psi|^2 = 1$

See these three plots for $P$ as a function of $\varphi$ for $n = 5$, this time not exceeding 1:

a) Plotting 
$$P = |\psi|^2 = |\sum_{k=0}^{n-1}\frac{1}{n}e^{ik\varphi}|^2 :$$

https://www.wolframalpha.com/input?i=plot+1%2F5%5E2+*+%7C1+%2B+e%5E%28i*phi%29+%2B+e%5E%28i*phi*2%29%2Be%5E%28i*phi*3%29%2Be%5E%28i*phi*4%29%7C%5E2+for+phi%3D0+to+2*pi

b) Plotting $P = \frac{1}{n^2}\left\vert \frac{1-e^{i n\varphi}}{1-e^{i\varphi}} \right\vert^2$. Note the $n^2$ in the denominator instead of $n$.

https://www.wolframalpha.com/input?i=plot+1%2F5%5E2+*+%7C%281+-+e%5E%28i*5*phi%29%29%2F%281-e%5E%28i*phi%29%29%7C%5E2+for+phi+%3D+0+to+2*pi

c) Plotting $P = \frac{1}{n^2} \frac{\sin^2 (n\frac{\varphi}{2})}{\sin^2 (\frac{\varphi}{2})}$. Note the $n^2$ in the denominator instead of $n$.


https://www.wolframalpha.com/input?i=plot+1%2F5%5E2+sin%5E2%285*phi%2F2%29%2Fsin%5E2%28phi%2F2%29+for+phi%3D0+to+2*pi

**Comment by thosgood** [comment]
of course! sorry, silly mistake on my behalf, and I'll merge these changes now :-) thank you again!

**Pull request merged**
